name: sphinx_mols
channels:
     - hjkgroup
     - conda-forge
     - anaconda
     - pytorch
     - defaults
dependencies:
     - libffi=3.2.1
     - openbabel=2.4.1
     - pip=20.0.2
     - numpy==1.16.4
     - scikit-learn=0.22.2.post1
     - pandas=1.0.3
     - scipy=1.4.1
     - keras=2.3.1
     - tensorflow=1.14.0